# Generated by Django 4.0.4 on 2022-05-02 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('thrust_newtons_sea_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('thrust_newtons_vacuum', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('specific_impulse_sea_level', models.IntegerField(default=0)),
                ('specific_impulse_vacuum', models.IntegerField(default=0)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RocketEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('stage', models.IntegerField(default=0)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.engine')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.rocket')),
            ],
        ),
        migrations.AddField(
            model_name='rocket',
            name='engines',
            field=models.ManyToManyField(through='engines.RocketEngine', to='engines.engine'),
        ),
    ]
