# Generated by Django 4.0.4 on 2022-05-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0002_engine_country_rocket_country_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='fuel_type',
            field=models.CharField(choices=[('OX', 'Oxidizer'), ('L', 'Liquid fuel'), ('S', 'Solid fuel')], default='L', max_length=2),
        ),
    ]
