# Generated by Django 4.0.4 on 2022-05-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0003_fuel_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
        ),
    ]
